const counties = [
    { key: 1, value: "Mombasa" },
    { key: 2, value: "Kwale" },
    { key: 3, value: "Kilifi" },
    { key: 4, value: "Tana River" },
    { key: 5, value: "Lamu" },
    { key: 6, value: "Taita/Taveta" },
    { key: 7, value: "Garissa" },
    { key: 8, value: "Wajir" },
    { key: 9, value: "Mandera" },
    { key: 10, value: "Marsabit" },
    { key: 11, value: "Isiolo" },
    { key: 12, value: "Meru" },
    { key: 13, value: "Tharaka-Nithi" },
    { key: 14, value: "Embu" },
    { key: 15, value: "Kitui" },
    { key: 16, value: "Machakos" },
    { key: 17, value: "Makueni" },
    { key: 18, value: "Nyandarua" },
    { key: 19, value: "Nyeri" },
    { key: 20, value: "Kirinyaga" },
    { key: 21, value: "Murang'a" },
    { key: 22, value: "Kiambu" },
    { key: 23, value: "Turkana" },
    { key: 24, value: "West Pokot" },
    { key: 25, value: "Samburu" },
    { key: 26, value: "Trans Nzoia" },
    { key: 27, value: "Uasin Gishu" },
    { key: 28, value: "Elgeyo/Marakwet" },
    { key: 29, value: "Nandi" },
    { key: 30, value: "Baringo" },
    { key: 31, value: "Laikipia" },
    { key: 32, value: "Nakuru" },
    { key: 33, value: "Narok" },
    { key: 34, value: "Kajiado" },
    { key: 35, value: "Kericho" },
    { key: 36, value: "Bomet" },
    { key: 37, value: "Kakamega" },
    { key: 38, value: "Vihiga" },
    { key: 39, value: "Bungoma" },
    { key: 40, value: "Busia" },
    { key: 41, value: "Siaya" },
    { key: 42, value: "Kisumu" },
    { key: 43, value: "Homa Bay" },
    { key: 44, value: "Migori" },
    { key: 45, value: "Kisii" },
    { key: 46, value: "Nyamira" },
    { key: 47, value: "Nairobi City" }
]

export {counties}